=== alion1992/LenguajeDeMarcas20252026/ud3/pruebasXSD/configuracion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="dependencies" >
<xs:complexType>
    <xs:sequence>
    <xs:element name="dependency" maxOccurs="unbounded">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="groupId">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-z.]+"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="artifactId">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-z-]+"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name ="scope">
                    <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="runtime"/>
                        <xs:enumeration value="compile"/>
                        <xs:enumeration value="test"/>
                        <xs:enumeration value="system"/>

                    </xs:restriction>
                    </xs:simpleType>

                </xs:element>
            </xs:sequence>
        </xs:complexType>

    </xs:element>
    </xs:sequence>

</xs:complexType>
</xs:element>
</xs:schema>

=== alion1992/LenguajeDeMarcas20252026/ud3/pruebasXSD/clase1405.xml
<?xml version="1.0" encoding="UTF-8"?>

<dependencies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="configuracion.xsd">
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
            <scope>compile</scope>
        </dependency>

         <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
</dependencies>
