=== alion1992/LenguajeDeMarcas20252026/ud3/ejercicioExpresionesRegulares/usuarios.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="usuarios">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="usuario" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="apellido" type="xs:string"/>

                            <xs:element name="email">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="telefono">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[67][0-9]{8}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="dni">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[0-9]{8}[A-Za-z]"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="codigoPostal">
                             <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[0-9]{5}"/>
                                    </xs:restriction>
                                </xs:simpleType>

                            </xs:element>   
                            
                            <xs:element name="username">
                             <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[a-z0-9._]{5,15}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>   



                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== alion1992/LenguajeDeMarcas20252026/ud3/ejercicioExpresionesRegulares/usuario.xml
<?xml version="1.0" encoding="UTF-8"?>
<usuarios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="usuarios.xsd">

    <usuario>
        <nombre>Juan</nombre>
        <apellido>Perez</apellido>
        <email>juan.perez@gmail.com</email>
        <telefono>612345678</telefono>
        <dni>12345678Z</dni>
        <codigoPostal>13065</codigoPostal>
        <username>juanp23</username>
        <password>Abc12345</password>
    </usuario>

    <usuario>
        <nombre>Ana</nombre>
        <apellido>Lopez</apellido>
        <email>ana.lopez@hotmail.com</email>
        <telefono>712345678</telefono>
        <dni>87654321X</dni>
        <codigoPostal>28080</codigoPostal>
        <username>ana_99</username>
        <password>Segura123</password>
    </usuario>

    <usuario>
        <nombre>Carlos</nombre>
        <apellido>Garcia</apellido>
        <email>carlos.garcia@empresa.es</email>
        <telefono>612000111</telefono>
        <dni>11223344A</dni>
        <codigoPostal>45001</codigoPostal>
        <username>carlos15</username>
        <password>Password1</password>
    </usuario>
</usuarios>
